/**
 * Credible Technologies Apps - data for landing and app pages.
 * Extracted from Google Play Store; icons/screenshots from Play Store CDN.
 */
window.CREDIBLE_APPS = [
  {
    id: 'com.prakshatech.appeight.appeight',
    slug: 'offline-metro-map',
    name: 'Offline Metro Map Delhi & more',
    tagline: 'Navigate India\'s Metro Networks Offline',
    shortDesc: 'Find routes, explore metro maps, and plan your journey—Delhi, Bengaluru, Mumbai—all without internet.',
    description: 'Offline Metro Map Delhi & more is your ultimate companion for navigating metro systems across India. Works 100% offline with multi-city support (Delhi Metro, Bengaluru Metro, Mumbai Metro), smart route finder, interactive maps, station search with fuzzy matching, fare calculator, and dark mode. Free forever.',
    playUrl: 'https://play.google.com/store/apps/details?id=com.prakshatech.appeight.appeight&hl=en_IN',
    icon: '🚇',
    iconUrl: 'https://play-lh.googleusercontent.com/Kls6Oo2eksoLjxneCpYz5OisezdIVU6f-VGmU-8wX4plx4fIkS3uXtnA_-wMVNLQQ_eVQzrPWvlBykknxO6XmQ=w240-h480-rw',
    screenshots: [
      'https://play-lh.googleusercontent.com/vfPi8H2qQ0NY8Kp86M8JdCAKLixsNu1kT8-KjahHBU8W5KuiNXplw44c9BdoofzrULkWgTj_AeDAp7-H34c7=w526-h296-rw',
      'https://play-lh.googleusercontent.com/V4HgwUWSz7_I8E_ycaTdvpiwKcoH123xKe1ZI_m-hBfGakhwfkKdlCi-0bBB4fpkzZVBR2XpLO5G_bR3erQbfg=w526-h296-rw',
      'https://play-lh.googleusercontent.com/vletybXR_6OtlUjxwK56F9QMQNGQObOytnC5bFwC4FfoyiIHeNc7ry2OMbhqBPV_STDmQE-Af0KU9ChwW0peOA=w526-h296-rw',
      'https://play-lh.googleusercontent.com/NwLJGZq9FZZtcxgH59CKXhD6mQZhCRaiGtWOo8mUUO8OHUQ8Am7gaQXYrsOY6FM3pzFZIAP8GyjwmNTX122-zA=w526-h296-rw',
      'https://play-lh.googleusercontent.com/16pQwLoepRknCvH7_eqvWidmcLrYBtDFpjD0EVGN21wzEpU8J4HyO5tOgx5KbrasKlbNaU5-QH0npUtQ5Rl0VrA=w526-h296-rw'
    ],
    category: 'Travel',
  },
  {
    id: 'com.prakshatech.appnine.appnine',
    slug: 'pro-pdf',
    name: 'Pro PDF: No Internet Edit/Read',
    tagline: '100% Offline PDF Editor',
    shortDesc: 'Edit, annotate, merge, split, and manage PDFs with complete privacy. No cloud, no subscriptions.',
    description: 'The privacy-focused PDF editor that works 100% offline. View, annotate (highlight, underline, sticky notes, shapes), add text, draw, merge & split PDFs, insert images and watermarks, headers & footers, crop pages, password protection, signatures, form filling. No data collection, no account required.',
    playUrl: 'https://play.google.com/store/apps/details?id=com.prakshatech.appnine.appnine&hl=en_IN',
    icon: '📄',
    iconUrl: 'https://play-lh.googleusercontent.com/kQHgjIOhWcqdjKNUqoOWjFWgJNZNfwSUyeYr2oqdvOqCsc7mu0GurZGejh5udd2BzxFN1vvGQTv914TnrsJ1vA=s128-rw',
    category: 'Tools',
  },
  {
    id: 'com.prakshatech.appxiv.appxiv',
    slug: 'compass',
    name: 'No Internet Compass App',
    tagline: 'Offline direction finder with Qibla, Vastu & Feng Shui',
    shortDesc: 'Find north, south, east, west and any direction accurately. Qibla for prayer, Vastu, Feng Shui, liturgical east. Works without internet.',
    description: 'Compass – Offline direction finder with Qibla, Vastu Shastra, Feng Shui & liturgical east. Uses your device\'s magnetic sensor. Set location once for correct Qibla bearing. 20 languages, light & dark theme. No account, no subscription. Free.',
    playUrl: 'https://play.google.com/store/apps/details?id=com.prakshatech.appxiv.appxiv&hl=en_IN',
    icon: '🧭',
    iconUrl: 'https://play-lh.googleusercontent.com/TKWmGVhy880MsMSNGyxkeo_sIIjqJlUUCGrSAvCI9ab3gwFihGIs1mzs9sararbNAUiO7bgRRjTQse8sLZPLhvw=s128-rw',
    category: 'Tools',
  },
  {
    id: 'com.prakshatech.appsix.appsix',
    slug: 'starfollow',
    name: 'StarFollow : Celebrity Monitor',
    tagline: 'Global Famous People Monitor',
    shortDesc: 'Track celebrities, get real-time news, and explore their stories on an interactive world map.',
    description: 'Stay connected with your favorite celebrities. Browse by category (actors, musicians, athletes, etc.), search by name or country, get news via Google News, view Wikipedia profiles and quotes, follow stars and see them on an interactive world map. Dark and light themes.',
    playUrl: 'https://play.google.com/store/apps/details?id=com.prakshatech.appsix.appsix&hl=en_IN',
    icon: '⭐',
    iconUrl: 'https://play-lh.googleusercontent.com/jm7jjyZYxCvPB1aasTdJzVC4p-g0kxmAvxBMXm9JTn2zqEpOuT-JOHcfjcji_ycM2S7hNftfydfbcxSmbPAD=s128-rw',
    category: 'Entertainment',
  },
  {
    id: 'com.prakshatech.appfive.appfive',
    slug: 'cat-directory',
    name: 'Cat Directory, Guide, Pet App',
    tagline: 'Cat Breeds, Care & Information',
    shortDesc: '100+ cat breed profiles, care tips, health education, and behavior guides—all offline.',
    description: 'A helpful reference for cat enthusiasts. Explore 100+ cat breed profiles with photos and traits, care guidelines (feeding, grooming, litter box), health education, and behavior basics. Save favorites, search and filter. General educational information only—not a substitute for veterinary advice.',
    playUrl: 'https://play.google.com/store/apps/details?id=com.prakshatech.appfive.appfive&hl=en_IN',
    icon: '🐱',
    iconUrl: 'https://play-lh.googleusercontent.com/1xGOcM7xBPBV7MpUbAL4oOIIdKxrOM4_5Zk9Svy7ewqXeZlquRcaPFKld2HmlWohMUatSfjwiS-gRvjRzL9X=s128-rw',
    category: 'Lifestyle',
  },
  {
    id: 'com.praksha.gali_cricket_app',
    slug: 'gali-cricket',
    name: 'Gali Cricket Scoring & Games',
    tagline: 'Score your street cricket matches—offline',
    shortDesc: 'Score matches without internet, save and share on WhatsApp, play cricket games with friends.',
    description: 'The perfect app for scoring street cricket offline. Save all matches, share scores on WhatsApp, live ball-by-ball commentary. Add unlimited players and overs, customize matches. Includes fun cricket games for when you\'re not on the ground. Free, simple, fast.',
    playUrl: 'https://play.google.com/store/apps/details?id=com.praksha.gali_cricket_app&hl=en_IN',
    icon: '🏏',
    category: 'Sports',
  },
  {
    id: 'com.prakshaappfour.appfour',
    slug: 'dog-directory',
    name: 'Dog Directory, Guide, Pets App',
    tagline: 'Your Complete Guide to Dog Breeds',
    shortDesc: '180+ dog breeds, compare breeds, track your dogs, and get care tips. Real photos, offline access.',
    description: 'Comprehensive dog breeds directory with 180+ breeds, detailed profiles, real photos, and breed comparison tool. My Dogs pet tracker: add dogs, schedules, growth timeline, reminders. Breed news, favorites, multiple themes. Export/import data. No ads option, completely free.',
    playUrl: 'https://play.google.com/store/apps/details?id=com.prakshaappfour.appfour&hl=en_IN',
    icon: '🐕',
    iconUrl: 'https://play-lh.googleusercontent.com/nhqbp0S7OG0DTW1SkzpYSkN4xBx20xyqSoh5KawBWlLxDiY-899fZ-feR5txs_w9oV1koZMg7kxVHRSmVSRzvw=s128-rw',
    category: 'Lifestyle',
  },
  {
    id: 'com.praksha.newyearwish',
    slug: 'wishing-status',
    name: 'Wishing Status & Story App',
    tagline: 'Create & share wishes for Status and Story',
    shortDesc: 'Pick image, add message and name, create and share on WhatsApp Status, Instagram, Facebook.',
    description: 'Create memorable greetings for WhatsApp Status, Instagram Stories, Facebook Stories. Pick image from gallery, choose language and message, add your name, choose position, create and share. Perfect for New Year, Republic Day, morning greetings, goodnight messages, festivals. Free with ads.',
    playUrl: 'https://play.google.com/store/apps/details?id=com.praksha.newyearwish&hl=en_IN',
    icon: '🎊',
    category: 'Social',
  },
  {
    id: 'com.prakshaapptwo.apptwo',
    slug: 'card-game',
    name: 'World Famous 22 Card Game Free',
    tagline: '22 classic card games from around the world—offline',
    shortDesc: 'Solitaire, Blackjack, Poker, Rummy, Teen Patti, Bridge, and more in one app.',
    description: 'Offline card games collection: Solitaire (Klondike, Spider, FreeCell, Pyramid), Casino (Blackjack, Video Poker, Hi-Lo), Classic (Rummy, Crazy Eights, War, Memory, Snap, Speed, Sevens), plus Teen Patti, Twenty-Eight, Dou Di Zhu, Durak, Brisca, Bridge. Free.',
    playUrl: 'https://play.google.com/store/apps/details?id=com.prakshaapptwo.apptwo&hl=en_IN',
    icon: '🃏',
    category: 'Games',
  },
  {
    id: 'com.prakshaappthree.appthree',
    slug: 'geopolitics',
    name: 'Geopolitics & Conflict Monitor',
    tagline: 'Real-Time Global Awareness',
    shortDesc: 'Track conflicts, geopolitics, and crises with an interactive map and verified multi-source news.',
    description: 'Stay informed about global conflicts, wars, and crises with a clear, real-time view. Interactive conflict map, verified data from UCDP, ReliefWeb, Reuters, BBC, Al Jazeera, and more. Multi-language news, custom RSS feeds. For students, journalists, analysts, and global citizens.',
    playUrl: 'https://play.google.com/store/apps/details?id=com.prakshaappthree.appthree&hl=en_IN',
    icon: '🌍',
    iconUrl: 'https://play-lh.googleusercontent.com/S4RI5GIuVI5q-FWAAG_PgXGiOK7X4AnVTi0YW3g5QFZdbbVZ6XAkvjrQtR6LQbhbwnY7mNoZz9DWVVAGrTSr-A=s128-rw',
    category: 'News',
  },
];
